"""add is_active to voyage_legs

Revision ID: 1994cf7c86ef
Revises: fe317af4dac5
Create Date: 2025-07-10 14:34:06.460830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1994cf7c86ef'
down_revision = 'fe317af4dac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voyage_legs', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voyage_legs', 'is_active')
    # ### end Alembic commands ###
