"""Add missing RTZ columns to routes table

Revision ID: 3652ea3139e5
Revises: b4b712744049
Create Date: 2025-12-25 15:33:16.571607

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3652ea3139e5'
down_revision = 'b4b712744049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cruises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lon', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hazard_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hazard_type', sa.String(length=100), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hazard_zones_geometry', 'hazard_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='uq_port_name_country')
    )
    op.create_table('route_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('file_content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_type_coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_type', sa.String(length=20), nullable=False),
    sa.Column('base_consumption_coef', sa.Float(), nullable=False),
    sa.Column('optimal_speed_knots', sa.Float(), nullable=False),
    sa.Column('fuel_cost_usd_tonne', sa.Float(), nullable=False),
    sa.Column('maintenance_impact', sa.Float(), nullable=False),
    sa.Column('methanol_consumption_ratio', sa.Float(), nullable=True),
    sa.Column('methanol_cost_usd_tonne', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('last_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_type')
    )
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('draft', sa.Float(), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('home_port', sa.String(length=50), nullable=True),
    sa.Column('fuel_efficiency_profile', sa.JSON(), nullable=True),
    sa.Column('operational_constraints', sa.JSON(), nullable=True),
    sa.Column('alternative_fuel_capability', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mmsi')
    )
    op.create_table('base_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('route_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_file_id'], ['route_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_base_routes_geometry', 'base_routes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cruise_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cruise_id'], ['cruises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyage_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cruise_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('departure_port_id', sa.Integer(), nullable=True),
    sa.Column('arrival_port_id', sa.Integer(), nullable=True),
    sa.Column('departure_lat', sa.Float(), nullable=True),
    sa.Column('departure_lon', sa.Float(), nullable=True),
    sa.Column('arrival_lat', sa.Float(), nullable=True),
    sa.Column('arrival_lon', sa.Float(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('leg_order', sa.Integer(), nullable=False),
    sa.Column('distance_nm', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cruise_id'], ['cruises.id'], ),
    sa.ForeignKeyConstraint(['departure_port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('alert_level', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_efficiency_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('voyage_leg_id', sa.Integer(), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=False),
    sa.Column('weather_wind_speed', sa.Float(), nullable=True),
    sa.Column('weather_wind_direction', sa.Float(), nullable=True),
    sa.Column('optimal_speed', sa.Float(), nullable=False),
    sa.Column('fuel_saving_percent', sa.Float(), nullable=False),
    sa.Column('estimated_savings_usd_hour', sa.Float(), nullable=False),
    sa.Column('efficiency_class', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=20), nullable=True),
    sa.Column('alternative_fuel_type', sa.String(length=20), nullable=True),
    sa.Column('alternative_fuel_savings', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.ForeignKeyConstraint(['voyage_leg_id'], ['voyage_legs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distance_nm', sa.Float(), nullable=True),
    sa.Column('eta_minutes', sa.Float(), nullable=True),
    sa.Column('base_route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_route_id'], ['base_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_legs_geometry', 'route_legs', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('route_leg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_leg_id'], ['route_legs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_waypoints_position', 'waypoints', ['position'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_waypoints_position', table_name='waypoints', postgresql_using='gist')
    op.drop_table('waypoints')
    op.drop_index('idx_route_legs_geometry', table_name='route_legs', postgresql_using='gist')
    op.drop_table('route_legs')
    op.drop_table('fuel_efficiency_calculations')
    op.drop_table('weather_statuses')
    op.drop_table('voyage_legs')
    op.drop_table('clocks')
    op.drop_index('idx_base_routes_geometry', table_name='base_routes', postgresql_using='gist')
    op.drop_table('base_routes')
    op.drop_table('ships')
    op.drop_table('ship_type_coefficients')
    op.drop_table('route_files')
    op.drop_table('ports')
    op.drop_table('locations')
    op.drop_index('idx_hazard_zones_geometry', table_name='hazard_zones', postgresql_using='gist')
    op.drop_table('hazard_zones')
    op.drop_table('cruises')
    # ### end Alembic commands ###