"""Add ships and fuel efficiency tables for maritime optimization

Revision ID: 42a73ecc6ca6
Revises: 71ffae1c4569
Create Date: 2025-10-26 14:46:06.409273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42a73ecc6ca6'
down_revision = '71ffae1c4569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ships table
    op.create_table('ships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mmsi', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('length', sa.Float(), nullable=True),
        sa.Column('draft', sa.Float(), nullable=True),
        sa.Column('built_year', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mmsi')
    )
    
    # Create fuel_efficiency_calculations table
    op.create_table('fuel_efficiency_calculations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ship_id', sa.Integer(), nullable=False),
        sa.Column('voyage_leg_id', sa.Integer(), nullable=True),
        sa.Column('fuel_saving_percent', sa.Float(), nullable=False),
        sa.Column('estimated_savings_usd_hour', sa.Float(), nullable=False),
        sa.Column('optimal_speed', sa.Float(), nullable=False),
        sa.Column('current_speed', sa.Float(), nullable=False),
        sa.Column('calculated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
        sa.ForeignKeyConstraint(['voyage_leg_id'], ['voyage_legs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_efficiency_calculations')
    op.drop_table('ships')
    # ### end Alembic commands ###