"""Add country field to ports and update voyage_leg

Revision ID: 43f4e680661d
Revises: 47e13818c202
Create Date: 2025-06-30 15:08:12.828726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f4e680661d'
down_revision = '47e13818c202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ports_name_key', 'ports', type_='unique')
    op.create_unique_constraint('uq_port_name_country', 'ports', ['name', 'country'])
    op.add_column('voyage_legs', sa.Column('departure_port_id', sa.Integer(), nullable=False))
    op.add_column('voyage_legs', sa.Column('arrival_port_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'voyage_legs', 'ports', ['arrival_port_id'], ['id'])
    op.create_foreign_key(None, 'voyage_legs', 'ports', ['departure_port_id'], ['id'])
    op.drop_column('voyage_legs', 'departure_port')
    op.drop_column('voyage_legs', 'arrival_port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voyage_legs', sa.Column('arrival_port', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('voyage_legs', sa.Column('departure_port', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voyage_legs', type_='foreignkey')
    op.drop_constraint(None, 'voyage_legs', type_='foreignkey')
    op.drop_column('voyage_legs', 'arrival_port_id')
    op.drop_column('voyage_legs', 'departure_port_id')
    op.drop_constraint('uq_port_name_country', 'ports', type_='unique')
    op.create_unique_constraint('ports_name_key', 'ports', ['name'])
    # ### end Alembic commands ###
