"""Add origin and capacity to cruises

Revision ID: 453d5441d5c5
Revises: e6bf137bbda9
Create Date: 2025-05-19 15:00:08.856103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453d5441d5c5'
down_revision = 'e6bf137bbda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cruises', 'destination',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cruises', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cruises', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cruises', 'destination',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
