"""Add geo fields to cruises and voyage_legs

Revision ID: 47e13818c202
Revises: da8da60a714f
Create Date: 2025-06-29 14:44:19.537052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e13818c202'
down_revision = 'da8da60a714f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruises', sa.Column('destination_lat', sa.Float(), nullable=True))
    op.add_column('cruises', sa.Column('destination_lon', sa.Float(), nullable=True))
    op.add_column('voyage_legs', sa.Column('departure_lat', sa.Float(), nullable=True))
    op.add_column('voyage_legs', sa.Column('departure_lon', sa.Float(), nullable=True))
    op.add_column('voyage_legs', sa.Column('arrival_lat', sa.Float(), nullable=True))
    op.add_column('voyage_legs', sa.Column('arrival_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voyage_legs', 'arrival_lon')
    op.drop_column('voyage_legs', 'arrival_lat')
    op.drop_column('voyage_legs', 'departure_lon')
    op.drop_column('voyage_legs', 'departure_lat')
    op.drop_column('cruises', 'destination_lon')
    op.drop_column('cruises', 'destination_lat')
    # ### end Alembic commands ###
