"""add routes and route_legs tables

Revision ID: 4cb5b0079192
Revises: 7c647aadeec2
Create Date: 2025-05-29 13:13:03.157683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cb5b0079192'
down_revision = '7c647aadeec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('cruises_backup')
    op.drop_table('payments')
    op.drop_constraint('cruises_location_id_fkey', 'cruises', type_='foreignkey')
    op.drop_column('cruises', 'cleaned_title')
    op.drop_column('cruises', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruises', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cruises', sa.Column('cleaned_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('cruises_location_id_fkey', 'cruises', 'locations', ['location_id'], ['id'])
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.create_table('cruises_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('departure_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('origin_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('origin_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='locations_pkey'),
    sa.UniqueConstraint('name', name='locations_name_key')
    )
    # ### end Alembic commands ###
