"""add_ship_coefficients_and_enhance_ships

Revision ID: 56456e05a868
Revises: 42a73ecc6ca6
Create Date: 2025-10-27 12:41:31.280492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '56456e05a868'
down_revision = '42a73ecc6ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ONLY ADD NEW FIELDS - DO NOT DROP EXISTING TABLES
    op.add_column('ships', sa.Column('home_port', sa.String(length=50), nullable=True))
    op.add_column('ships', sa.Column('fuel_efficiency_profile', sa.JSON(), nullable=True))
    op.add_column('ships', sa.Column('operational_constraints', sa.JSON(), nullable=True))
    op.add_column('ships', sa.Column('alternative_fuel_capability', sa.Boolean(), nullable=True, server_default='false'))
    
    # Add new fields to fuel_efficiency_calculations
    op.add_column('fuel_efficiency_calculations', sa.Column('weather_wind_speed', sa.Float(), nullable=True))
    op.add_column('fuel_efficiency_calculations', sa.Column('weather_wind_direction', sa.Float(), nullable=True))
    op.add_column('fuel_efficiency_calculations', sa.Column('efficiency_class', sa.String(length=10), nullable=True))
    op.add_column('fuel_efficiency_calculations', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('fuel_efficiency_calculations', sa.Column('algorithm_version', sa.String(length=20), nullable=True, server_default='v2.0_sandbox'))
    op.add_column('fuel_efficiency_calculations', sa.Column('alternative_fuel_type', sa.String(length=20), nullable=True))
    op.add_column('fuel_efficiency_calculations', sa.Column('alternative_fuel_savings', sa.Float(), nullable=True))
    
    # Create ONLY the new coefficients table
    op.create_table('ship_type_coefficients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ship_type', sa.String(length=20), nullable=False),
        sa.Column('base_consumption_coef', sa.Float(), nullable=False),
        sa.Column('optimal_speed_knots', sa.Float(), nullable=False),
        sa.Column('fuel_cost_usd_tonne', sa.Float(), nullable=False),
        sa.Column('maintenance_impact', sa.Float(), nullable=False),
        sa.Column('methanol_consumption_ratio', sa.Float(), server_default='1.8'),
        sa.Column('methanol_cost_usd_tonne', sa.Float(), server_default='850'),
        sa.Column('validation_status', sa.String(length=20), server_default='validated'),
        sa.Column('last_calibration_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ship_type')
    )
    
    # Keep the voyage_legs improvements that make sense
    op.alter_column('voyage_legs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('voyage_legs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('voyage_legs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove only the fields we added
    op.drop_column('ships', 'home_port')
    op.drop_column('ships', 'fuel_efficiency_profile')
    op.drop_column('ships', 'operational_constraints')
    op.drop_column('ships', 'alternative_fuel_capability')
    
    op.drop_column('fuel_efficiency_calculations', 'weather_wind_speed')
    op.drop_column('fuel_efficiency_calculations', 'weather_wind_direction')
    op.drop_column('fuel_efficiency_calculations', 'efficiency_class')
    op.drop_column('fuel_efficiency_calculations', 'confidence_score')
    op.drop_column('fuel_efficiency_calculations', 'algorithm_version')
    op.drop_column('fuel_efficiency_calculations', 'alternative_fuel_type')
    op.drop_column('fuel_efficiency_calculations', 'alternative_fuel_savings')
    
    op.drop_table('ship_type_coefficients')
    
    op.alter_column('voyage_legs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('voyage_legs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('voyage_legs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###