"""Add weather_statuses table

Revision ID: 5b8991110124
Revises: 5eeab2e5bad5
Create Date: 2025-07-07 13:29:03.606160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8991110124'
down_revision = '5eeab2e5bad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_legs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_legs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('departure_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('arrival_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('distance_nm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_time_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('leg_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name='route_legs_route_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='route_legs_pkey')
    )
    # ### end Alembic commands ###
