"""Add route and hazard tables

Revision ID: 968f83e64475
Revises: bfd27dfe1413
Create Date: 2025-09-16 14:22:49.341712
"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = '968f83e64475'
down_revision = 'bfd27dfe1413'
branch_labels = None
depends_on = None


def upgrade():
    # ### Commands auto generated by Alembic - adjusted manually ###

    # Create table to store uploaded RTZ or related route files
    op.create_table(
        'route_files',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('filename', sa.String(255), nullable=False),
        sa.Column('uploaded_at', sa.DateTime, server_default=sa.func.now(), nullable=False)
    )

    # Create base_routes table for each route definition
    op.create_table(
        'base_routes',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('route_file_id', sa.Integer, sa.ForeignKey('route_files.id')),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text, nullable=True)
    )

    # Create route_legs table for route segmentation
    op.create_table(
        'route_legs',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('base_route_id', sa.Integer, sa.ForeignKey('base_routes.id')),
        sa.Column('sequence', sa.Integer, nullable=False),
        sa.Column('start_time', sa.DateTime, nullable=True),
        sa.Column('end_time', sa.DateTime, nullable=True),
        sa.Column('geometry', sa.Text, nullable=True)  # To be replaced with Geometry(PostGIS)
    )

    # Create waypoints table for individual points along a route leg
    op.create_table(
        'waypoints',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('route_leg_id', sa.Integer, sa.ForeignKey('route_legs.id')),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('geometry', sa.Text, nullable=True)  # To be replaced with Geometry(PostGIS)
    )

    # Create hazard_zones table for dangerous areas (ice, rocks, restricted areas)
    op.create_table(
        'hazard_zones',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('hazard_type', sa.String(100), nullable=True),
        sa.Column('geometry', sa.Text, nullable=False)  # To be replaced with Geometry(PostGIS)
    )

    # ### End Alembic commands ###


def downgrade():
    # ### Commands auto generated by Alembic - adjusted manually ###
    op.drop_table('hazard_zones')
    op.drop_table('waypoints')
    op.drop_table('route_legs')
    op.drop_table('base_routes')
    op.drop_table('route_files')
    # ### End Alembic commands ###
