"""Add extended fields to dummy_users

Revision ID: bfd27dfe1413
Revises: 8dc99e5c91de
Create Date: 2025-07-29 14:38:31.566153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd27dfe1413'
down_revision = '8dc99e5c91de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('dummy_users', sa.Column('nationality', sa.String(length=50), nullable=True))
    op.add_column('dummy_users', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('dummy_users', sa.Column('preferred_sailing_areas', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_users', 'preferred_sailing_areas')
    op.drop_column('dummy_users', 'language')
    op.drop_column('dummy_users', 'nationality')
    op.drop_column('dummy_users', 'gender')
    # ### end Alembic commands ###
