"""Add voyage_legs table

Revision ID: da8da60a714f
Revises: 8a9851ba6148
Create Date: 2025-06-12 13:58:08.048444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da8da60a714f'
down_revision = '8a9851ba6148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyage_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cruise_id', sa.Integer(), nullable=False),
    sa.Column('departure_port', sa.String(length=100), nullable=False),
    sa.Column('arrival_port', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('leg_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cruise_id'], ['cruises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('payments', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table('voyage_legs')
    # ### end Alembic commands ###
