"""Add nullable departure_port_id and arrival_port_id to voyage_legs

Revision ID: dff0bc311b7c
Revises: 5e69322f5e60
Create Date: 2025-07-01 15:00:50.835877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff0bc311b7c'
down_revision = '5e69322f5e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ports_name_key', 'ports', type_='unique')
    op.create_unique_constraint('uq_port_name_country', 'ports', ['name', 'country'])
    op.add_column('voyage_legs', sa.Column('departure_port_id', sa.Integer(), nullable=True))
    op.add_column('voyage_legs', sa.Column('arrival_port_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'voyage_legs', 'ports', ['departure_port_id'], ['id'])
    op.create_foreign_key(None, 'voyage_legs', 'ports', ['arrival_port_id'], ['id'])
    op.drop_column('voyage_legs', 'departure_port')
    op.drop_column('voyage_legs', 'arrival_port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voyage_legs', sa.Column('arrival_port', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('voyage_legs', sa.Column('departure_port', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voyage_legs', type_='foreignkey')
    op.drop_constraint(None, 'voyage_legs', type_='foreignkey')
    op.drop_column('voyage_legs', 'arrival_port_id')
    op.drop_column('voyage_legs', 'departure_port_id')
    op.drop_constraint('uq_port_name_country', 'ports', type_='unique')
    op.create_unique_constraint('ports_name_key', 'ports', ['name'])
    # ### end Alembic commands ###
