"""Add origin to cruises

Revision ID: e6bf137bbda9
Revises: 68429fc567a8
Create Date: 2025-05-19 14:46:09.274660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bf137bbda9'
down_revision = '68429fc567a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruises', sa.Column('origin', sa.String(length=100), nullable=True))
    op.add_column('cruises', sa.Column('destination', sa.String(length=100), nullable=True))
    op.add_column('cruises', sa.Column('origin_lat', sa.Float(), nullable=True))
    op.add_column('cruises', sa.Column('origin_lon', sa.Float(), nullable=True))
    op.add_column('cruises', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruises', 'capacity')
    op.drop_column('cruises', 'origin_lon')
    op.drop_column('cruises', 'origin_lat')
    op.drop_column('cruises', 'destination')
    op.drop_column('cruises', 'origin')
    # ### end Alembic commands ###
