"""
Learning extraction module
Extracts learnings and insights from YOUR_PLAN.md
"""

import re
from datetime import datetime

class LearningExtractor:
    """Extracts learnings from project documentation"""
    
    def __init__(self, config):
        self.config = config
    
    def extract_todays_learnings(self):
        """
        Extract learnings from YOUR_PLAN.md file
        
        Returns:
            list: List of learning items
        """
        if not self.config.PLAN_FILE.exists():
            print(f"Warning: Plan file not found: {self.config.PLAN_FILE}")
            return []
        
        try:
            with open(self.config.PLAN_FILE, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Extract learnings section
            learnings = self._extract_learning_section(content)
            
            # Also look for learnings in the entire document
            all_learnings = self._find_learning_keywords(content)
            
            # Combine and deduplicate
            combined = list(set(learnings + all_learnings))
            
            # Save learnings to file
            if combined:
                self._save_learnings(combined)
            
            return combined
            
        except Exception as e:
            print(f"Error extracting learnings: {e}")
            return []
    
    def _extract_learning_section(self, content):
        """Extract learnings from specific sections in the plan"""
        learnings = []
        
        # Pattern for learning sections
        patterns = [
            r'### Today\'s Learnings.*?\n(.*?)(?=\n###|\n##|\n---|$)',
            r'## Learning Insights.*?\n(.*?)(?=\n##|\n---|$)',
            r'Key Takeaways.*?\n(.*?)(?=\n##|\n---|$)',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, content, re.IGNORECASE | re.DOTALL)
            if match:
                section_content = match.group(1)
                # Extract list items
                items = re.findall(r'^[\s]*[•\-\*]\s*(.+)$', section_content, re.MULTILINE)
                items += re.findall(r'^[\s]*\d+\.\s*(.+)$', section_content, re.MULTILINE)
                learnings.extend(items)
        
        return [item.strip() for item in learnings if item.strip()]
    
    def _find_learning_keywords(self, content):
        """Find learning statements using keywords"""
        learnings = []
        
        # Split into sentences
        sentences = re.split(r'[.!?]+', content)
        
        for sentence in sentences:
            sentence = sentence.strip()
            if any(keyword in sentence.lower() for keyword in self.config.LEARNING_KEYWORDS):
                # Clean up the sentence
                clean_sentence = self._clean_learning_sentence(sentence)
                if clean_sentence and len(clean_sentence.split()) >= 3:
                    learnings.append(clean_sentence)
        
        return learnings
    
    def _clean_learning_sentence(self, sentence):
        """Clean and format learning sentence"""
        # Remove markdown formatting
        clean = re.sub(r'[*_`#]', '', sentence)
        # Remove extra whitespace
        clean = re.sub(r'\s+', ' ', clean).strip()
        # Capitalize first letter
        if clean:
            clean = clean[0].upper() + clean[1:]
        
        return clean
    
    def _save_learnings(self, learnings):
        """Save learnings to a markdown file"""
        if not learnings:
            return
        
        # Create filename with date
        filename = self.config.LEARNINGS_DIR / f"learnings_{self.config.today_str}.md"
        
        content = f"""# Learnings - {self.config.today_str}
*Extracted from YOUR_PLAN.md*

## Summary
Found {len(learnings)} learning item(s) today.

## Learning Items

"""
        
        for i, learning in enumerate(learnings, 1):
            content += f"{i}. {learning}\n"
        
        content += f"""

---
*Auto-generated by BergNavn Progress Tracker*
*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(content)
        except Exception as e:
            print(f"Warning: Could not save learnings: {e}")