"""
Report generation module
Creates weekly and monthly progress reports
"""

from datetime import datetime, timedelta

class ReportGenerator:
    """Generates progress reports"""
    
    def __init__(self, config):
        self.config = config
    
    def generate_weekly_report(self, git_data, learnings):
        """Generate a weekly progress report"""
        report_content = self._create_report_content(git_data, learnings)
        
        # Save to weekly report file
        report_file = self.config.PROGRESS_DIR / "weekly_report.md"
        
        try:
            with open(report_file, 'w', encoding='utf-8') as f:
                f.write(report_content)
            
            print(f"✅ Weekly report saved to: {report_file}")
            
        except Exception as e:
            print(f"Error saving weekly report: {e}")
    
    def _create_report_content(self, git_data, learnings):
        """Create the content for the weekly report"""
        
        # Get date range for the report
        end_date = datetime.now()
        start_date = end_date - timedelta(days=7)
        
        report_date = end_date.strftime('%Y-%m-%d')
        
        content = f"""# 📊 Weekly Progress Report
**BergNavn Shipping Optimization Project**
*Report Period: {start_date.strftime('%Y-%m-%d')} to {report_date}*
*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

---

## 📈 Project Overview

This report summarizes the progress made on the BergNavn shipping optimization project.

### Key Statistics
- **Report Period**: Last 7 days
- **Analysis Date**: {report_date}
- **Project Focus**: Real-time maritime route optimization with AIS, weather data, and risk assessment

---

## 🖥️ Development Activity

### Git Commit Summary
"""
        
        # Add Git activity summary
        if git_data and git_data.get('total_commits', 0) > 0:
            content += self._format_git_summary(git_data)
        else:
            content += "No Git activity recorded in the analysis period.\n\n"
        
        # Add learnings section
        content += "## 📚 Learning Insights\n\n"
        
        if learnings:
            content += f"Found **{len(learnings)}** learning item(s) this week:\n\n"
            for i, learning in enumerate(learnings, 1):
                content += f"{i}. {learning}\n"
            content += "\n"
        else:
            content += "No specific learnings extracted this week.\n\n"
        
        # Add recommendations
        content += self._generate_recommendations(git_data, learnings)
        
        # Add footer
        content += f"""---

## 🔮 Project Outlook

### Current Status
The project is actively developed with focus on:
1. Real-time data pipeline integration
2. Risk engine development
3. Dashboard interface improvements

### Next Week Focus
Based on current progress, consider focusing on:
1. Completing current development tasks
2. Documenting key learnings
3. Planning next development phase

---

## 📝 Notes

This report is auto-generated by the BergNavn Progress Tracking System.
For detailed commit history, refer to the Git repository.
For project plan and specifications, see YOUR_PLAN.md.

*Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        return content
    
    def _format_git_summary(self, git_data):
        """Format Git activity summary for report"""
        
        total_commits = git_data.get('total_commits', 0)
        active_days = git_data.get('activity_metrics', {}).get('active_days', 0)
        streak = git_data.get('activity_metrics', {}).get('current_streak_days', 0)
        
        summary = f"""
**Total Commits**: {total_commits}
**Active Days**: {active_days}
**Current Streak**: {streak} day(s)
**Most Active Day**: {git_data.get('activity_metrics', {}).get('most_active_day', 'N/A')}

### Commit Categories
"""
        
        commit_analysis = git_data.get('commit_analysis', {})
        commit_types = commit_analysis.get('commit_types', {})
        
        for commit_type, count in commit_types.items():
            if count > 0:
                summary += f"- **{commit_type.title()}**: {count} commit(s)\n"
        
        # Add meaningful commits info
        meaningful_commits = sum(1 for c in git_data.get('commits', []) 
                               if c.get('is_meaningful', False))
        
        if total_commits > 0:
            meaningful_percent = (meaningful_commits / total_commits) * 100
            summary += f"\n**Meaningful Commits**: {meaningful_commits} ({meaningful_percent:.1f}%)\n"
        
        summary += "\n"
        return summary
    
    def _generate_recommendations(self, git_data, learnings):
        """Generate recommendations based on analysis"""
        
        recommendations = []
        
        # Check commit frequency
        if git_data and git_data.get('total_commits', 0) < 3:
            recommendations.append(
                "Consider increasing commit frequency to better track progress. "
                "Aim for at least one meaningful commit per working day."
            )
        
        # Check learning documentation
        if len(learnings) == 0:
            recommendations.append(
                "Document key learnings in YOUR_PLAN.md. This helps track "
                "knowledge growth and provides valuable insights for future reference."
            )
        
        # Check commit message quality
        if git_data:
            commits = git_data.get('commits', [])
            short_messages = sum(1 for c in commits if len(c.get('message', '').split()) < 3)
            
            if short_messages > len(commits) * 0.5:  # More than 50% are short
                recommendations.append(
                    "Improve commit message quality. Write descriptive messages "
                    "that explain the 'why' behind changes, not just the 'what'."
                )
        
        if not recommendations:
            return "## ✅ Recommendations\n\nGood progress! Keep up the current workflow.\n\n"
        
        content = "## 🎯 Recommendations\n\n"
        for i, rec in enumerate(recommendations, 1):
            content += f"{i}. {rec}\n"
        
        content += "\n"
        return content